server:
  port: 7079
spring:
  application:
    name: JRTP701-MajorProj07-CorrospondanceAPI
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/jrtp701-ishdb
    username: root
    password: 1234

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect
mail:
    host: smtp.gmail.com
    username: kavi20900@gmail.com
    password: tzzgcionenfrrscf
    properties:
        mail: 
          transport:
            protocol: smtp
          smtp:
            port: 587
            auth: true
            starttls: 
              enable: true
              required: true    
mailbody:
    registeruser:
         location: src/main/java/com/nt/service/user_registration_body.txt
    recoverpwd:
         location: src/main/java/com/nt/service/recover_pwd_body.txt
