spring:
  application:
    name: JRTP701-MajorProj07-DataCollectionService
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/jrtp701db
    username: root
    password: 1234

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect

server:
  port: 8085

ar:
  ssa-web:
    url: http://localhost:9090/ssa-web-api/find/{ssn}
  state: california
